import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Achintha Alahakoon",
  description: "Generated by create next app",
  icons: {
    icon: "/Images/aa.jpg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-950 text-slate-50`}
      >
        <div className="flex min-h-screen flex-col">
          <Navbar />
          <main className="flex-1">{children}</main>
          <footer className="border-t border-slate-800 bg-slate-950/95">
            <div className="mx-auto flex max-w-5xl justify-center px-6 py-4 text-xs text-slate-500">
              <span>
                Copyright &copy; {new Date().getFullYear()} Achintha Alahakoon
              </span>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
